### ISSUE TITLE
Activity feed backedn MVP

### ISSUE THREAD

**Issue by mkolar** [ynput/ayon-backend#117]

**Comment by BigRoy** [comment]
This seems to be lacking some info. I'm sure Martin knows what to do however.

**Comment by dee-ynput** [comment]
> This seems to be lacking some info. 

Hi Roy
We're testing a new workflow with GitHub projects. If everything goes well, you might see a lot of those 'draft issues' from now on.

Feel free to give us feedback from your PoV about this! This new workflow should fit your needs too 😌

I guess discord would be a good place for those discussion, at least while we are just testing out the workflow.

Cheers!
