### ISSUE TITLE
Requirements and compatibility definition for addon versions

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#123]
## Story

With the evergrowning list of Ayon addons and the fast pace of development, developers need a way
to declare which version of Ayon and other addons their addon is compatible with.

## Problem

Some addons may not work with certain versions of Ayon or other addons. In that case, the bundle
may not work as expected or may not work at all. This can lead to a bad user experience and a lot of
confusion.

Unfortunately REZ manifest don't provide a way to specify version constraints in the way that
we need, so we shoul aim to extend the manifest file to include this information.

## Proposal

Addon manifest (`package.py`) should contain the following information. 
Version compatibility is provided using "poetry" style version constraints (comma separated list of version ranges).

Checking will be performed using [semver.match](https://python-semver.readthedocs.io/en/2.9.0/api.html#semver.match)

Ayon already enforces semver versioning for addons and will use this information to check compatibility.

This won't break compatibility with existing addons, nor the REZ ecosystem.

### `ayon_server_version: str`

This key is already supported in the manifest file. It specifies the version of Ayon server that the addon is compatible with.

### `ayon_launcher_version: str`

This key specifies the version of the Ayon launcher that the addon is compatible with.

### `ayon_required_addons: dict[str, str]`

List of required addons and their version constraints. 
Bundle won't be created if any of the required addons are missing or incompatible.

### `ayon_compatible_addons: dict[str, str]`
List of compatible addons and their version constraints.
If an addon is present in the bundle, it should be compatible with the specified version range.

Bundle may be created even if some of the addons are not compatible, but the user will be warned.

## Example

```python

name = "example"
title = "Example addon"
version = "2.5.0"

plugin_for = ["ayon_server"]
build_command = ""

ayon_server_version = ">=1.0.8,<2.0.0"
ayon_launcher_version = ">1.5.0"

ayon_required_addons =  {
    "addon1": ">=0.1.0",
    "addon2": ">=0.1.0",
}
ayon_compatible_addons = {
    "addon3": ">=0.1.0",
    "addon4": ">=0.1.0",
}
```

**Comment by martastain** [comment]
fair enough. we already use `ayon_version` key, but since it is not used that much, i think i could just make it an alias and for ayon_server_version, deprecate it and eventually start log warnings that it should be changed.

**Comment by iLLiCiTiT** [comment]
> Bundle may be created even if some of the addons are not compatible, but the user will be warned.

I don't think this is correct. The compatible versions is for validation of addons that are not required, but the version validation is important, or?

**Comment by BigRoy** [comment]
> Unfortunately REZ manifest don't provide a way to specify version constraints in the way that
> we need, so we shoul aim to extend the manifest file to include this information.

Could you explain why it does not? What does it fail to support or do?

**Comment by iLLiCiTiT** [comment]
> What does it fail to support or do?

It does not support semver. And you can't define what is described here as `compatible_addons` -> when the addon does not require to have the other addon, but if the addon is there then you are compatible with specific range of version.

**Comment by BigRoy** [comment]
> It does not support semver.

Doesn't that mean that in essence the `rez` ecosystem itself is incompatible with the versioning usages in AYON? Is there then still a place for `rez` in what we're doing?

> when the addon does not require to have the other addon, but if the addon is there, then you are compatible with specific range of version.

Didn't `rez` have 'soft requirements', like "do not force to load it, but if present it must be in this range". It seems ["Weak References"](https://rez.readthedocs.io/en/stable/basic_concepts.html#weak-references) is exactly that?

> Also this is used for validation of compatibility, not sure if rez can tell if your set of defined packages are compatible with each other in a way, that you can get & display the information in a nice way.

I believe there is a way to have it provide a detailed trace as to _where_ the conflict arises between used packages. How and where that is used and whether it's up to par with how we like to display it I have no idea. Do you have an example of how we're currently displaying that? Like, what's the preferred design now of how we're displaying it? Likely we can check with the Rez community how we can get to similar output from Rez if needed?

**Comment by iLLiCiTiT** [comment]
> Like, what's the preferred design now of how we're displaying it? Likely we can check with the Rez community how we can get to similar output from Rez if needed?

I would say that it should be possible to get list of all incompatibilities, with detailed version information.
So you can display something like:
```
- Maya addon requires Deadline >=1.0.1
- Core addon requires AYON launcher 1.1.0
- ...
```
Bringing thoughts that, I would also like to see marked addon version enumerator if is not compatible with something, that would have tooltip with these details.

> Doesn't that mean that in essence the rez ecosystem itself is incompatible with the versioning usages in AYON? Is there then still a place for rez in what we're doing?

I would ask different question: Is there a place for rez, when all we need is to check compatibility of addon versions?
