### ISSUE TITLE
Events payload including what service had created a event

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/ayon-backend#132]
At the moment it is impossible to filter out all events with all service users from particular service. This way we could avoid processing loops only from particular services and keep others. 

In ShotGrid for example we are no filtering all events for entity attrib changes but we can only avoid loop with getting all users which are set as `isService` and then enroll an event which would be avoiding those so we are not looping events. But this will in future probably create some issue if for example under the same worker will run Ftrack and what ever is changed in here we will need to be reflected in ShotGrid.

**Comment by jakubjezek001** [comment]
We had discuss it now with @iLLiCiTiT and Ftrack and Kitsu would also benefit.

**Comment by martastain** [comment]
superseded by https://github.com/ynput/ayon-backend/issues/391
