### ISSUE TITLE
Any user should be able to update a checkbox

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-backend#134]
### Story

- A sup writes feedback as checklist tasks to complete. The artist checks off the list items as they complete them.

### Current behaviour

- Only the author can update their own comments.

### Expected

- Anyone can update a checklist item in the comment body.
- Checklist values in the body look like this `* [ ]` or `* [x]`.

**Comment by martastain** [comment]
I am not sure about this one. Shouldn't be the original author responsible for marking it as checked? The reason for marking it as checked may be resolved in the conversation and that way there would be a track of why and who is responsible for it. If anyone could modify it, it might bring anarchy. 

From the technical perspective, it is tricky - doable, but tricky - the patch request would need to check what exactly was changed in the body and be aware of the markdown structure. So I'd rather have a broader discussion first before I implement this.

**Comment by mkolar** [comment]
Definitely must be possible by the artist. That's the point. Super provides a checklist to do, the artist goes through it and when they are done, the work is up for review again. Supe can go back and see whether artist addressed the issues based on the checklist and that informs how they review. 

not Supes job to be checking each item, they just need to see the new state of work, once all items were done. Github deals with it this way....showing the last editors of the comments 

![Image](https://github.com/ynput/ayon-backend/assets/3333008/e2d42fa4-9580-4668-886f-e03eda9ad03b)

**Comment by mkolar** [comment]
> Okay. So we will also need activity edit history available on each activity.

I would say so. It's one of those things that simplifies disputes and misunderstandings. But still a valid question on how to deal with the checkboxes. Feels to me that they are the only thing that should be editable by others, so it's not quite the same as actual comment editing. 

As a stretch goal I was going to suggest aggregating all the checkboxes from comments under and entity so we could show it at a checklist with it's completion state, similar to GH, CU, trello and many other systems.

**Comment by Innders** [comment]
This ia test
