### ISSUE TITLE
Include assignee fullName in activityData

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-backend#135]
Currently there is only an "assignee" field with the user's name.

It would be great if the assignee's fullName was also included somewhere.

<img width="424" alt="image" src="https://github.com/ynput/ayon-backend/assets/49156310/cf338123-13ad-437c-bd44-5517f89252f7">

![SCR-20240414-mbwc](https://github.com/ynput/ayon-backend/assets/49156310/9a08afe5-f8ec-491d-afe4-840198544bc2)

**Comment by martastain** [comment]
`activityData` field contains the raw data stored in the database. although it could be convenient to store fullName (and other metadata) there, it would cause problem when an user changes their profile during the lifetime of the project. So i'd stick with storing just the `name` here and create a graphql field similar to author for assignee (which would have the same structure, but also could be null wen the activity is not `assignee.*`.
