### ISSUE TITLE
Create events to track user login and logout

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#156]
## Story

For statistics, we need to keep track when a user logged in and out - when they were last active. At the moment, we can only see whether user is logged in at the moment (has active sessions), but for users disconnected for longer than session TTL, we don't have a way of telling whether their account is used or not (and and maybe disable it automatically)

## Proposed solution

- [x] Create `user.log_in` event whenever a session is created
- [x] Create `user.log_out` event when a session is invalidated/expired
- [x] Create `user.log_fail` event when maximum login attempts is reached (tracking suspicious activity)
- [x] Add additional session information (geolocation, IP) to the event (tracking suspicious activity)

**Comment by martastain** [comment]
tagging @MustafaJafar

**Comment by MustafaJafar** [comment]
I believe this'd be cool to have.
It will allow creating addons for user tracking/monitoring.
