### ISSUE TITLE
Attachments: configure the file size limit

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-backend#171]
Where will this setting live?

**Comment by martastain** [comment]
Hmmm. @dee-ynput 
This is probably worth a discussion. Should we have a global limit for attachments and reviewables (separately)? 
Or is this rather per-project? Or maybe also per user?

**Comment by martastain** [comment]
Depends on https://github.com/ynput/ayon-backend/issues/337

**Comment by dee-ynput** [comment]
> Hmmm. [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/152978560?s=64&amp;u=a0de62727b8c0f4c1b95632e06a34220ab040da1&amp;v=4">@dee-ynput](https://github.com/dee-ynput) This is probably worth a discussion. Should we have a global limit for attachments and reviewables (separately)? Or is this rather per-project? Or maybe also per user?

Let's set a global limit, as server config.

**Comment by dee-ynput** [comment]
Actually, after internal discussions, let's consider this later if it surfaces again 👍
