### ISSUE TITLE
Relative imports issue

### ISSUE THREAD

**Issue by victorbartel** [ynput/ayon-backend#2]
Is there any reason to privilege relative imports like `from .access import AccessToAssigned, AccessToHierarchy` to the global ones(a la namespace)? For testing purposes, it's crucial. Have a look at [one](https://github.com/Ellipsanime/shotgrid-leecher/tree/0.0.9/api) of our projects, if you are wondering how fast-api, global imports and pytest can work together.

I understand that you are traversing a prototyping phase, but tests should be first class citizens within your project from the very beginning. Relative imports do not arrange a thing.

**Comment by BigRoy** [comment]
This seems unanswered and old. Is this still relevant?

@victorbartel could you elaborate on why it'd make much of a difference? Why do you feel that a package with relative imports would fail to support testing?
