### ISSUE TITLE
Endpoint: Entity ID to URI

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-backend#215]
## Story

For use in USD workflows and Asset Resolution, we need centralized endpoint that will take project and entity ID and returns valid URL.

### Problems

This will solve places on pipeline side of things where we need to translate already existing IDs (for example representation IDs) to their URI form to feed them as paths for USD asset resolver (in loaders) and it is needed for the new representation model.

**Comment by BigRoy** [comment]
Isn't this basically:

- `http://{server}/api/projects/{project_name}/representations/{representation_id}`?

The same exists for folder ids, version ids, etc. already.

Or did you mean to have a generic one that "returns any entity type" and just returns any matching type that happens to have that ID? How reliable is that? Are ids enforced to be unique even across folders to representations?

**Comment by antirotor** [comment]
to be more precise - not http, but

```
ayon+entity://project/folder?product&version&representation
```

if you have just representation id, you need to trace back to put together everything else and it would be good to have central "source of truth" for that.

**Comment by martastain** [comment]
complement to `/api/resolve/`

`/api/unresolve` or `/api/dissolve` .... hmmmmm :)

**Comment by antirotor** [comment]
> complement to `/api/resolve/`
> 
> `/api/unresolve` or `/api/dissolve` .... hmmmmm :)

yep, I like `/api/antiresolve`

**Comment by BigRoy** [comment]
I see - an endpoint taking a `representation id` turning it into the `ayon+entity` URI equivalent.
