### ISSUE TITLE
Activity feed: Comment entity suggestions

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#221]
## Story

Auto-suggestions for entities in comments should be resolved server-side using a dedicated endpoint

### Problems

Currently the frontend has to call various graphql queries, often nested to get a list of entities for autocompletion.

### Proposal

REST endpoint `[POST] /api/projects/{projectName}/suggest` with the body

```json
{
  "entityType": ""
  "entityId": ""
}
```

returning

```json
{
    "tasks": [
        {
            "createdAt": "2024-04-17T13:13:16.202057+00:00",
            "id": "408bd0d2fcbc11ee9ea50242ac140004",
            "name": "matchmove",
            "parent": {
                "createdAt": "2024-04-17T13:13:16.201230+00:00",
                "folderType": "Shot",
                "id": "408bb084fcbc11ee9ea50242ac140004",
                "name": "sh030"
            },
            "relevance": 0.0,
            "taskType": "Matchmove",
            "thumbnailId": "ada3ff4c717a42b2bd21ed653955404e"
        }
    ],
    "users": [
        {
            "fullName": "Viviane Renard",
            "name": "demouser37",
            "relevance": 15.0
        },
        {
            "fullName": "Isabel García",
            "name": "demouser45",
            "relevance": 15.0
        }
    ],
    "versions": [
        {
            "createdAt": "2024-04-17T13:13:16.234911+00:00",
            "id": "4090d460fcbc11ee9ea50242ac140004",
            "parent": {
                "createdAt": "2024-04-17T13:13:16.233779+00:00",
                "id": "4090a8a0fcbc11ee9ea50242ac140004",
                "name": "animationChar2",
                "productType": "animation",
                "relevance": 0.0
            },
            "relevance": 0.0,
            "version": 1
        }
    ]
```

Response model covers common fields of folders, tasks and versions (more or less) and the list should be returned sorted by relevance. One request for all mentionable entities should be returned (apart from the users as they are already available in the frontend anyways)

**Comment by Innders** [comment]
Looks good. A couple extra fields I will need.

- `createdAt` so it can display how long ago a version was created
- `parent` parent of the entity one level up
     **Version:** `{type: "product", subType: "render", name: "genericRender", id: "XXXX" }`
     **Task:** `{type: "folder", subType: "shot", name: "shot010", label: "Shot010", id: "XXXX" }`

![image](https://github.com/ynput/ayon-backend/assets/49156310/5cc72a2a-7df8-48ef-9590-7098e7b88ac3)

**Comment by Innders** [comment]
Here is what I show for each entity type.

### Folders

**Assignees:** Every assignee in the project
**Versions:** Disabled - what versions would you want to see on a folder?
**Tasks:** Direct child tasks of the folder.

### Tasks

**Assignees:** Every assignee in the project, sorted by assignees first.
**Versions:** Every version linked to the task.
**Tasks:** Direct sibling tasks to the task.

### Versions

**Assignees:** Every assignee in the project, sorted by author first.
**Versions:** Direct sibling versions to the version.
**Tasks:** Direct sibling tasks to the parent task of the version.

**Comment by Innders** [comment]
In some ways I think assignees could have it's own endpoint as well.

The sorting of assignees right now is very dumb and usually A-Z.

For mentions it could be way smarter by first suggesting:

- Assignee/author of the task/version.
- Users that have already commented on the entity.
- The last user to comment on the entity.
- Users that **you** tag often (ranked lists of users comments and their tags).
- Users that surround the entity (users on sibling tasks).
