### ISSUE TITLE
Authentication: Assigned projects are not propagated to existing sessions

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#223]
## Story

When a user is logged in and they are assigned to a new project, this information does not propagate to existing session and the user has to log in again to see the project

**Comment by martastain** [comment]
Waiting for steps to reproduce. The server seems to work as expected.
@m-u-r-p-h-y , @iLLiCiTiT

**Comment by Innders** [comment]
Is this a FE cache issue? Is the issue fixed when refreshing the page?

**Comment by martastain** [comment]
> Is this a FE cache issue? Is the issue fixed when refreshing the page?

Actually the problem in this case seems to be in the launcher - new assignments propagate correctly in the frontend and when you assign a user to a project, the project shows in the project list on the web, but not in the launcher.

**Comment by iLLiCiTiT** [comment]
It happened on a client side. We asked them to contact us when the issue happens again.

**Comment by m-u-r-p-h-y** [comment]
> @m-u-r-p-h-y I guess we didn't get this error reported since then? Can we consider this as resolved?
It was not reported from anyone for quite a while. I agree to close the issue and reopen if needed.
