### ISSUE TITLE
Market: Improve endpoints

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-backend#244]
1. Be more consistent with endpoint naming. This should probably be `Get Market Addon List`? (this is a breaking change so probably not worth doing).
2. Provide better response shape as at the moment it's `null`.

![image](https://github.com/ynput/ayon-backend/assets/49156310/f9b367da-4a80-43ea-9c5f-84280addf13f)

Endpoints:

Market Addon List - https://ayon.dev/docs#tag/Market/operation/market_addon_list
Market Addon Detail - https://ayon.dev/docs#tag/Market/operation/market_addon_detail
Market Addon Version Detail - https://ayon.dev/docs#tag/Market/operation/market_addon_version_detail

**Comment by dee-ynput** [comment]
I'd say that it is indeed a breaking change, but we probably have zero external code using it.
The sooner we do it the less people it will annoy.
Let's do it ASAP then :)

**Comment by martastain** [comment]
It shouldn't break anything. Responses are supposed to be exactly the same. Only the response models are now documented.
