### ISSUE TITLE
User Settings: Manager cannot make themselves a developer

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-backend#263]
### To reproduce

1. Login as a manager
2. Go to `/users/settings`
3. Try to set yourself as a developer
4. Good response but stays false.
5. You can only set users with "user" level to developer not any other managers or admins.

### Expected behavior

You can at least set yourself as a developer.
Can you set other managers and admins?

**Comment by martastain** [comment]
I believe this is the correct behavior - developer mode is only available to admins. Should this change? Most of the stuff developer mode affects is admin-only anyways.

**Comment by Innders** [comment]
Fixing in https://github.com/ynput/ayon-frontend/issues/597
