### ISSUE TITLE
Anatomy: Define Status per Entity Type

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-backend#275]
**Domains**: review, scene building, version pushing/pulling
**Personas**: Sup, Artist

## Problem
Among the versions of a product, one may be "Approved". This information is needed in Loader tools/UI. But more than one version can have a given status, and some statuses may have apply to only some entity types.

## Proposal
- **ayon-backend**: We add the ability to define different statuses per entity types in Anatomy.
- **ayon-core**: https://github.com/ynput/ayon-core/issues/784

**Comment by martastain** [comment]
We already have something similar for attributes. where it's called "scopes". I'd use the same convention here:

```python
    scope: list[ProjectLevelEntityType] | None= Field(
        default=None,
        title="Scope",
        description="List of entity types the status is available on. None for all entities",
        example=["task"],
```

**Comment by mkolar** [comment]
Agreed. The same approach can be used for statuses.
