### ISSUE TITLE
resolver: Strip_SDF_FORMAT_ARGS_from_uri

### ISSUE THREAD

**Issue by Lypsolon** [ynput/ayon-backend#284]
## Story

When sending a URI with `:SDF_FORMAT_ARGS:order=100` or similar, the resolver endpoint will receive an internal server error. 
The target is to strip the SDF_FOMRAT_ARGS so that URIs with this extra data will still work. 

### Problems

Allow sending uris with `:SDF_FORMAT_ARGS` and get them resolved by the server. 

### Proposal

use the following regX to remove the SDF_FOMRAT_ARGS from the end of the URI `:SDF_FORMAT_ARGS.[^:]*$`

**Comment by martastain** [comment]
Closing as duplicate https://github.com/ynput/ayon-backend/issues/283
