### ISSUE TITLE
Resolver: Sane responses in the case of errors

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#286]
## Story

Currently `/api/resolve` does not correctly handle malformed URIs as mentioned here https://github.com/ynput/ayon-backend/issues/283

### Problems

When a malformed URI is present in the request, the entire request fails with error 500 (which implies a server problem rather than client).

### Proposal

- When a request contains a malformed uri, 400 response should be returned instead, keeping 500 for real errors
- Add `canFail` option to the request model, that would allow skipping erroring URIs instead of failing the entire query similarly to `/api/projects/{projectName}/operations` - in that case, skipped entities could be either simply excluded (similarly as they were missing) or included with a status code per record

Tagging @dee-ynput @Lypsolon and @BigRoy for visibility

**Comment by BigRoy** [comment]
> Currently /api/response does not correctly handle malformed URI

I'm sure you meant `/api/resolve`?

What the best return code or behavior is I'm not sure, I'm not expert in web requests and responses so I'll leave this to others. Just wanted to remark that at least being able to identify which of the responses was invalid would be very nice if possible.

**Comment by martastain** [comment]
> I'm sure you meant `/api/resolve`?

sorry. fixed :)
