### ISSUE TITLE
Entity: Field 'data' returns 'None' if empty

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/ayon-backend#288]
## Story
When receiving entity thad does not have any keys in `"data"` field, it does return `None` instead of empty dictionary.

### To reproduce
1. Fetch task using rest api or graphql (request field `data` in case of graphql).
2. If task does not have filled any data it will contain `None`. If they are filled it will return expected dictionary.

### Expected behavior
It should return empty dictionary instead of `None`.

### Additional context
I guess the behavior is connected to previous data field implementation as it was permissions based and it was not possible to get them via graphql.

**Comment by martastain** [comment]
Handled in ayon-python-api
