### ISSUE TITLE
Access Groups: getAccessGroups types

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-backend#331]
The types are quite bare for getAccessGroups and getAccessGroupsSchema.

![image](https://github.com/user-attachments/assets/91609650-4164-4ceb-b7bd-85b64fd548c3)

**Comment by martastain** [comment]
getAccessGroupSchema returns JSONschema. similarly to `settings/schema` it is never accessed directly from TS code, it is just passed as is to rjsf. I'll have a look if i can pass the types to getAccessGroups.
