### ISSUE TITLE
Server configuration

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-backend#337]
Create a consistent set of endpoints for server configuration CRUD.

Server configuration uses a BaseSettingsModel. settings are stored in `public.config.serverConfig` and there's no staging/production differentiation and the setting model is updated with the server. stored configuration is updated automatically.

**Comment by dee-ynput** [comment]
I think this was archived by mistake (automation triggered by setting status to Planned)

I'll revive it as Ready in the backlog.
Feel free to re-archive it if it was intentional @martastain
