### ISSUE TITLE
Migrate Settings: Bundle migration fails to transfer certain settings.

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-backend#350]
## Story

There has been a report that updating certain addons with bundle migration fail to transfer certain setting overrides. Specifically:

```
Applications :   0.1.4  --> 1.0.0
Core :           0.1.4  --> 0.4.4
Unreal :         0.1.0  --> 0.2.2
```

Settings that failed to copy:
```
Settings-->Applications-->Applications Definitions-->Blender   :    Environment  and variants

Settings-->Core-->Publish Plugins-->Collect Anatomy Instance Data-->Follow Workfile Version-->Active
Settings-->Core-->Tools-->Publish-->Template name profiles
Settings-->Core-->Publish Plugins-->Integrate Hero Version-->Active-->OFF
Settings-->Core-->Tools-->Workfiles-->Open last workfile on launch
```

![migrate](https://github.com/user-attachments/assets/6b09cb5f-1f30-40d1-9220-78b818c436b0)

_The issue may be due other things - that's still being investigated on discord [here](https://discord.com/channels/517362899170230292/563751989075378201/1285214105053167689)_

### To reproduce

1. Create bundle with those old addon versions
2. Apply the mentioned settings
3. Create new bundle with the new addon versions
4. Copy/migrate bundle settings

### Expected behavior

Copy should work - or if possible log a warning when it fails.

## Environment

- **Server version**: 1.4.1+202409160911
- **Server host OS**: 
- **Browser**: 
- **Client version**: 

### Additional context

Reported on [discord](https://discord.com/channels/517362899170230292/563751989075378201/1285180617910390784)

**Comment by BigRoy** [comment]
This was down to the old addon versions (very old versions) being incompatible with recent ayon-server versions. 

See additional logs:

[logs2.txt](https://github.com/user-attachments/files/17015804/logs2.txt)
[logs.txt](https://github.com/user-attachments/files/17015805/logs.txt)

![errors](https://github.com/user-attachments/assets/839f9b95-2a74-4fef-910f-8c21ab8d5876)

[_source on discord_](https://discord.com/channels/517362899170230292/563751989075378201/1285215271795298425)

1. AYON server 1.4.1 fixes that backwards compatibility for old ayon site sync addons. 
2. Old ayon-applications addons had some logic that created applications enumerators dynamically - unfortunately that old code does not like the new style ayon applications addon starting from 1.0.0+. So unfortunately, the only workaround to that is to remove ayon-applications 1.0.0 addon from your server, install latest ayon-applications 0.2.x version and then copy settings there. Then remove the legacy addons, and install the ayon-applications 1.0.0+.

---

Whether that explains why ayon-core and ayon-unreal settings did not transfer I'm not sure. @martastain ?

**Comment by martastain** [comment]
@BigRoy I wasn't able to reproduce the issue with the exact versions of core and unreal addons you provided. Do you think it is still the issue or was this fixed in the meanwhile? All settings were copied during migration just fine. Tested both studio and project overrides.
