### ISSUE TITLE
Inbox: Status changes clogging important tab

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-backend#367]
## Story

I'm a producer or supervisor and will be watching 100s of tasks. As the artist changes the status of tasks my inbox important tab becomes overloaded with status change notifications (based on real feedback).

### Problems

The user never uses the inbox because it's too hard to use.
Status changes for producers and sups are rarely useful.
Status changes importance is linked to the users role (artist, producer, supervisor) and the status itself.

### Proposal

All status changes are considered **not** important.
In the future we could look at settings that allow for specific status changes to become important. `Not ready -> Ready to Start` `In progress -> In review`

## TODO

- [ ] All status change activities are non important regardless of watchers.

**Comment by martastain** [comment]
Closed by https://github.com/ynput/ayon-backend/pull/398
