### ISSUE TITLE
Settings: Field definition supports tagging

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-backend#460]
## Story

When defining a setting Field, devs should be able to specify tags picked up by UI filtering/slicing.
Example tags could be:
- Complexity Level: Level1/Level2/Level2, or Beginer/Advanced/Pro/God
- Domain: Modeling/Texture/Lookdev/.../Dev/Tracking/...

**Comment by martastain** [comment]
You can do that already. SettingsField supports tags:list[str] argument that was added to address this. 

As we discussed, we can follow github-like notation (complexity:easy, domain:excel).
