### ISSUE TITLE
How to set Redis and Postgres URLs via environment variables?

### ISSUE THREAD

**Issue by loonghao** [ynput/ayon-backend#96]
Hi,

We are want to deploy Ayon using Kubernetes, and we have existing Redis and Postgres services within our infrastructure. 
I would like to know how to configure these services using environment variables.

Thanks!

**Comment by martastain** [comment]
Hi,
It is possible using `AYON_POSTGRES_URL` and `AYON_REDIS_URL` 

BTW: the list of all accepted env vars and their defaults could be extracted from here (just add `ayon_` prefix)
https://github.com/ynput/ayon-backend/blob/develop/ayon_server/config.py

We'll find a way how to propagate this to the documentation.
